# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  database: ccc
  host: localhost
  username: root
  password: b0953733650
  timeout: 50000

test:
  adapter: mysql2
  encoding: utf8
  database: ccc
  host: localhost
  username: root
  password: b0953733650
  timeout: 50000

production:
  adapter: mysql2
  encoding: utf8
  database: ccc
  username: root
  password: b0953733650
  password: 1111
  timeout: 50000
